### ISSUE TITLE
Remove solution to TreeConstructorTwo

### ISSUE THREAD

**Issue by danielmurray** [codecog/code-challenge-solutions#1]
Howdy Josh,
I am the creator of the TreeConstructorTwo problem, and I am currently using it to assess candidates for my company. I would appreciate if you removed your solution from this repository.
Dan

**Comment by codecog** [comment]
no problem at all, have updated the file and rewrote the git history to remove the solution in the original commit.

**Comment by danielmurray** [comment]
Thanks Josh, 'preciate it.
